# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx485tffg1157-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.cache/wt [current_project]
set_property parent.project_path C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/countCheck.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/manSubtractor.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/incrementer.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/loadChannel.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/adrMux.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/storeChannel.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/arbiterController.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/dataMux.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/loadIDComparator.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/fifo.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/fullChannel.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/arbiterTop.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/DMAControllerSta.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/adapter.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/src/twoChannelSetUpBuffered.vhd
  C:/Users/Sygnious/Documents/Skole/MASTER/VHDL/Vivado/DMA/DMA.srcs/sources_1/imports/new/DMAToplevel.vhd
}
catch { write_hwdef -file DMATopLevel.hwdef }
synth_design -top DMATopLevel -part xc7vx485tffg1157-1
write_checkpoint DMATopLevel.dcp
catch { report_utilization -file DMATopLevel_utilization_synth.rpt -pb DMATopLevel_utilization_synth.pb }
